name: Findr
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 17.0
targets:
  Findr:
    type: application
    platform: iOS
    sources:
      - path: Findr/Findr
        excludes:
          - "**/*.md"
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.findr
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "iPhone Developer"
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1,2
    info:
      path: Findr/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
